server:
  port: 8080
spring:
  application:
    name: news
  config:
    activate:
      on-profile: dev
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        naming:
          physical-strategy: by.clevertec.configuration.CustomPhysicalNamingStrategy
        format_sql: true
        generate_statistics: true
        jdbc:
          batch_size: 4
          order_inserts: true
        dialect:
          org:
            hibernate:
              dialect: PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/news-dev
    username: postgres
    password: root
  liquibase:
    enabled: true
    contexts: dev
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  output:
    ansi:
      enabled: ALWAYS
logging:
  file:
    name: news/logs_dev.log
  level:
    org.springframework.web: WARN
    org.hibernate: WARN
    root: ERROR
    by.clevertec.aspect: INFO
  logback:
    rollingpolicy:
      max-file-size: 10MB
cache:
  type: lru
  capacity: 100
---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/news-test
    username: postgres
    password: root
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        naming:
          physical-strategy: by.clevertec.configuration.CustomPhysicalNamingStrategy
        format_sql: true
        generate_statistics: true
        jdbc:
          batch_size: 4
          order_inserts: true
        dialect:
          org:
            hibernate:
              dialect: PostgreSQLDialect
  liquibase:
    enabled: true
    contexts: test
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  output:
    ansi:
      enabled: ALWAYS
logging:
  file:
    name: news/logs_test.log
  level:
    org.springframework.web: DEBUG
    org.hibernate.stat: INFO
    org.hibernate.sql: DEBUG
    root: WARN
    by.clevertec.aspect: INFO
  logback:
    rollingpolicy:
      max-file-size: 10MB
cache:
  type: lru
  capacity: 100
