spring:
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        naming:
          physical-strategy: by.clevertec.configuration.CustomPhysicalNamingStrategy
        format_sql: true
        generate_statistics: true
        jdbc:
          batch_size: 4
          order_inserts: true
        dialect:
          org:
            hibernate:
              dialect: PostgreSQLDialect
---
spring:
  config:
    activate:
      on-profile: dev
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/news-dev
    username: postgres
    password: 6%Itrlfkp765
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/news-test
    username: postgres
    password: 6%Itrlfkp765